//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by tank.rc
//
#define IDC_DELETE                      3
#define IDC_MORE                        3
#define IDC_SEND                        3
#define IDS_APP_TITLE                   103
#define IDC_EXIT                        105
#define IDC_TANK                        109
#define IDD_DIALOG_CONTROLS             153
#define IDI_BIG                         162
#define IDD_SELECT_OBJECT               163
#define IDD_DIALOG_GETKEY               178
#define IDD_SAVE                        183
#define IDD_LOAD                        184
#define IDD_GETFILENAME                 184
#define IDD_OTHER_DT                    186
#define IDD_NEWMAP3                     187
#define IDD_OBJPROP                     187
#define IDD_ADVANCED                    195
#define IDD_ADDPLAYER                   199
#define IDD_IMPORT                      200
#define IDD_EXPORT                      201
#define IDD_NEWDM                       202
#define IDD_OPTIONS                     203
#define IDD_WINAMP_CONTROL              204
#define IDD_MAIN                        222
#define IDD_MSGBOX_OKCANCEL             224
#define IDD_MSGBOX_OK                   225
#define IDD_MSGBOX_YESNO                226
#define IDD_PLAYERS                     227
#define IDC_CONNECT                     236
#define IDC_CREATE                      238
#define IDD_CREATESERVER                239
#define IDD_CONNECT                     240
#define IDD_NETPLAYERS                  241
#define IDM_MAPSETTINGS                 242
#define IDD_MAP_SETTINGS                243
#define IDD_NEWMAP                      244
#define IDR_RT_MANIFEST1                244
#define IDD_DISPLAY                     245
#define IDR_241                         245
#define IDC_CHK_PARTICLES               1000
#define IDC_CHK_DAMLABEL                1002
#define IDC_CHK_AICH                    1003
#define IDC_RADIO_KEYBOARD              1004
#define IDC_CHK_FPS                     1004
#define IDC_RADIO_MOUSE                 1005
#define IDC_CHK_TIMER                   1005
#define IDC_RADIO_HYBRID                1006
#define IDC_CHK_SHOWSELECTMODE          1006
#define IDC_CLOSE                       1007
#define IDC_RADIO_MOUSE2                1007
#define IDC_OBJECTLIST                  1008
#define IDC_RADIO_KEYBOARD2             1008
#define IDC_NEWGAME                     1008
#define IDC_OK                          1009
#define IDC_OPTIONS                     1009
#define IDC_CANCEL                      1010
#define IDC_PLAYERS                     1010
#define IDC_T                           1011
#define IDC_LOAD                        1011
#define IDC_SAVE                        1012
#define IDC_LIST                        1013
#define IDC_FILENAME                    1014
#define IDC_EDITOR                      1014
#define IDC_DT                          1015
#define IDC_X                           1015
#define IDC_DT_SPIN                     1016
#define IDC_X_SPIN                      1016
#define IDC_FPS                         1017
#define IDC_Y                           1017
#define IDC_DT_SPIN2                    1018
#define IDC_Y_SPIN                      1018
#define IDC_RATE                        1022
#define IDC_ADD                         1023
#define IDC_KICK                        1024
#define IDC_NAME                        1025
#define IDC_PLATERSETUP                 1025
#define IDC_PLAYERSETUP                 1025
#define IDC_SKIN                        1026
#define IDC_TYPE                        1027
#define IDC_TITLE                       1028
#define IDC_TEAM                        1028
#define IDC_FRAGLIMIT                   1029
#define IDC_CLASS                       1029
#define IDC_SPEED                       1030
#define IDC_TIMELIMIT                   1031
#define IDC_SPIN_FL                     1032
#define IDC_SPIN_TL                     1033
#define IDC_ALLOW_EDITOR                1034
#define IDC_NETWORKSPEED                1034
#define IDC_ALLOW_EDITPLAYERS           1035
#define IDC_SPIN_NW                     1035
#define IDC_MAPLIST                     1036
#define IDC_PLRLIST                     1037
#define IDC_LATENCY                     1037
#define IDC_SPIN_NW2                    1038
#define IDC_SPIN_LATENCY                1038
#define IDC_NIGHTMODE                   1039
#define IDC_VOLUME                      1040
#define IDC_SPIN_SPEED                  1041
#define IDC_INTRO                       1042
#define IDC_PREVIEW                     1043
#define IDC_MAXSOUNDS                   1044
#define IDC_TEXT                        1045
#define IDC_SETTINGS_PLAYER1            1051
#define IDC_SETTINGS_PLAYER2            1052
#define IDC_SETTINGS_PLAYER3            1053
#define IDC_SETTINGS_PLAYER4            1054
#define IDC_SETTINGS_WINAMP             1055
#define IDC_ACC_0                       1056
#define IDC_ACC_1                       1057
#define IDC_ACC_2                       1058
#define IDC_ACC_3                       1059
#define IDC_ACC_4                       1060
#define IDC_INDICATOR                   1061
#define IDC_STATUSWINDOW                1070
#define IDC_INFO                        1071
#define IDC_CHAT                        1072
#define IDC_INPUT                       1073
#define IDC_EDIT                        1074
#define IDC_MAPINFO                     1078
#define IDC_DESC                        1080
#define IDC_URL                         1082
#define IDC_SCROLL_AREA                 1082
#define IDC_AUTHOR                      1083
#define IDC_EMAIL                       1084
#define IDC_THEME                       1086
#define IDC_LIST1                       1088
#define IDC_SERVERS                     1088
#define IDC_RENDER_OPENGL               1089
#define IDC_RENDER_DIRECT3D             1090
#define IDC_FULLSCREEN                  1091
#define IDC_RESOLUTION                  1092
#define IDC_BPP                         1094
#define IDC_HOTSEAT                     3268
#define IDM_NEWGAME                     32771
#define IDM_REALTIME                    32774
#define IDM_DT_50                       32776
#define IDM_DT_17                       32777
#define IDM_DT_13                       32778
#define IDM_DT_12                       32779
#define IDM_DT_10                       32780
#define IDM_DT_8                        32781
#define IDM_DT_7                        32782
#define IDM_DT_1                        32783
#define IDM_DT_OTHER                    32784
#define IDM_SETTINGS_PLAYER1            32788
#define IDM_SETTINGS_PLAYER2            32789
#define IDM_SETTINGS_PLAYER3            32790
#define IDM_SETTINGS_PLAYER4            32791
#define IDM_SAVE                        32792
#define IDM_MODE_GAME                   32793
#define IDM_MODE_EDITOR                 32794
#define IDM_ACC_0                       32795
#define IDM_ACC_1                       32796
#define IDM_ACC_2                       32797
#define IDM_ACC_3                       32798
#define IDM_ACC_4                       32799
#define IDM_ADVANCED                    32800
#define IDM_OPTIONS                     32802
#define IDM_EXPORT                      32803
#define IDM_IMPORT                      32804
#define IDM_EMPTYMAP                    32805
#define IDM_SETTINGS_WINAMP             32806
#define IDM_LOAD                        32807
#define IDC_STATIC                      -1

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        246
#define _APS_NEXT_COMMAND_VALUE         32808
#define _APS_NEXT_CONTROL_VALUE         1097
#define _APS_NEXT_SYMED_VALUE           111
#endif
#endif
